Mark all as read
heroku/telex pull request #129
Opened 2020-09-18 19:27 UTC by mwoods79

GUS [W-8070355](https://gus.lightning.force.com/a07B0000008d1QVIAY)

Enterprise customers (mostly SFDC and Heroku) can have many thousands of notifications. Currently when I user visits `https://dashboard.heroku.com/notifications` they see a button that says "Mark All As Read". Dashboard enqueues a notification read request for each of the notifications for that user.

Because of other work we are doing around rate limiting (DOS protection) in particleboard we noticed large spikes in requests for certain users. Turns out, if a SFDC employee in Germany clicks "Mark All As Read" it will enqueue 21k+ notification requests from the browser.

This PR will allow dashboard to make one request instead of 25k.

2020-09-18 19:59 UTC, mwoods79 commented on lib/mediators/notifications/read_all.rb
> +        .where(Sequel.lit("notifications.created_at > now() - '1 month'::interval"))
I am only marking newer notifications as read. This is b/c the lister logic seems to only show the last months worth of notifications to users.

https://github.com/heroku/telex/blob/859aa7e81ac637d1d89072fdf26eeac7be177a17/lib/mediators/notifications/lister.rb#L11

2020-09-22 16:04 UTC, wbarn requested changes

2020-09-22 16:04 UTC, wbarn commented on lib/mediators/notifications/read_all.rb
> +        .where(Sequel.lit("notifications.created_at > now() - '1 month'::interval"))
If the existing button click marks ALL things as read then I think we could just do the same here?

2020-09-22 16:30 UTC, mwoods79 commented
@wbarn the current code is the existing behavior. If we load 20k messages then we makr 20k messages as read. Removing this code will mark all things as read even in the past (messages that don't show up as valid). I'm not sure if Telex has some worker that eventually cleans up notifications but removing this could potentially mark a lot of notifications as read per user. 

I'm fine with removing this, just want you to understand what the implications are, and that this is not current behavior.

2020-09-23 17:46 UTC, wbarn approved these changes
@mwoods79 Ah I understand now. Thanks for the clarification! I'll approve and get this shipped today.

2020-09-23 18:39 UTC, merged